### DISCUSSION TITLE
creation of inverse predicates

### DISCUSSION THREAD

**Discussion by MaFi2000** [morph-kgc/morph-kgc#322] [Ideas]
**Background**
In RDF properties are not bidirectional but rather pointing in one direction. Therefore many ontologies provide inverse properties such as:

```ttl
:Bob :hasDaughter :Alice .
:Alice :isDaughterOf :Bob .
```

If you want to transform data using morph_kgc, you have to create two triples Maps with two different subjectMaps.

**Requirement**
It would be very helpful, if there was a feature that creates the inverse without having two separate triples map.

idea:
```ttl
<#Testmap>
    rml:predicate :hasDaughter ;
    rml:inversePredicate :isDaughterOf ;
    rml:objectMap
        [
            rml:constant :Alice ;
            rml:termType rml:IRI ;
        ].
```

**Comment by arenas-guerrero-julian** [comment]
This can be already done in Morph-KGC with YARRRML. Example 69 from [YARRRML spec](https://rml.io/yarrrml/spec/):

```yml
mappings:
  work:
    predicateobjects:
      - predicates: ex:createdBy
        inversepredicates: ex:created
        objects: $(foafprofile)
        type: iri
```
