### DISCUSSION TITLE
Best way to write RML mappings to create and link each distinct URI with its textual label from exploded multi-value cell entries

### DISCUSSION THREAD

**Discussion by ariannamorettj** [morph-kgc/morph-kgc#327] [Ideas]
For the purposes of our project, my colleague @sbrzt and I decided to extend the data model to add human-readable lables, associated with some IRIs we generate from a field which could contain multiple values, and that we already extract and separate using an extension of the built-in value-explode function.

For instance, in the "Subjects" column, one cell holds the values "ermafrodita; busto; braccio", separated by semicolons (see Figure 1).

<img width="245" alt="image" src="https://github.com/user-attachments/assets/22deea8f-f66d-49af-80e5-284f0bcee795" />

Fig 1

 After processing and converting the data to RDF, each individual value is represented as an instance of crm:E73_Information_Object, all linked to the same controlled term in the AAT using crm:P2_has_type (see Figure 2). Each of these instances shares the same class and type; what differs is the URI assigned to each crm:E73_Information_Object. 

<img width="392" alt="image" src="https://github.com/user-attachments/assets/767cb3de-d181-49d6-98b8-4efd576f0c49" />

Fig 2

Figure 3 illustrates the RDF output for one specific value, "ermafrodita".

<img width="742" alt="image" src="https://github.com/user-attachments/assets/459a3b81-c118-4aae-a12c-3d8c02f14864" />

Fig 3

Mapping and functions currently used to obtain this result are represented below:

**Mapping**:
```
subjects:
    sources:
      - 'sample_input_file.csv~csv'
    s:
      function: idlab-fn:normalize_and_convert_to_iri
      parameters:
        - parameter: idlab-fn:valueParams
          value:
            # Passaggio 1: Esplodere i soggetti multipli
            function: idlab-fn:multiple_separator_split_explode
            parameters:
              - parameter: idlab-fn:list_param_string_sep
                value: ";---,--- e ---\n--- + --- - ---\r"
              - parameter: idlab-fn:valParam
                value: $(Soggetti)
        - parameter: idlab-fn:valueType
          value: "sub"
        - parameter: idlab-fn:valueNum
          value: ""
      type: iri
    po:
      - [ a, "crm:E73_Information_Object" ]
      - ["crm:P2_has_type", "aat:300404126"]
```

**Functions**:

```
@udf(
    fun_id='http://example.com/idlab/function/normalize_and_convert_to_iri',
    str_param='http://example.com/idlab/function/valueParams',
    type_param='http://example.com/idlab/function/valueType',
    num_param='http://example.com/idlab/function/valueNum',
    parent_param='http://example.com/idlab/function/valueParent'
)

def normalize_and_convert_to_iri(str_param, type_param, num_param, parent_param=None):
    # Rimuovi tutto ciò che è compreso tra parentesi tonde o quadre, inclusi gli stessi
    str_param = re.sub(r"[\(\[].*?[\)\]]", "", str_param)

    str_param = str_param.strip().lower()
    str_param = unicodedata.normalize('NFKD', str_param).encode('ascii', 'ignore').decode('ascii')
    str_param = re.sub(r"\s+", " ", str_param)
    str_param = str_param.replace(' ', '_')
    str_param = str_param.replace('"', '')
    str_param = str_param.replace('.', '_')
    str_param = str_param.strip('_')
    str_param = re.sub(r"_+", "_", str_param)
    if not parent_param:
        if num_param == "":
            to_return = "".join([prefisso, type_param, "/", str_param, "/", versione])
            return to_return
        else:
            to_return = "".join([prefisso, type_param, "/", str_param, "/", num_param, "/", versione])
            return to_return
    else:
        if num_param == "":
            to_return = "".join([prefisso, type_param, "/", str_param,"_parent", "/", versione])
            return to_return
        else:
            to_return = "".join([prefisso, type_param, "/", str_param,"_parent", "/", num_param, "/", versione])
            return to_return
```

```
@udf(
    fun_id="http://example.com/idlab/function/multiple_separator_split_explode",
    string='http://example.com/idlab/function/valParam',
    separators_list_str='http://example.com/idlab/function/list_param_string_sep')

def multi_sep_string_split_explode(string, separators_list_str):
    separators_list = separators_list_str.split("---")
    for s in separators_list:
        string = string.replace(s, "---")
    string_list = string.split("---")
    clean_string_list_exploded = [x.strip() for x in string_list if x]
    return([el for el in clean_string_list_exploded if el])
```

In addition to that, what we would like to do now —though we’re not yet sure how—is to enrich each of these crm:E73_Information_Object instances with an additional property, crm:P1_is_identified_by, linking it to a new instance of crm:E41_Appellation. **each with its own URI** (**the label is different for each URI, but for each one of these entities, both the URI and the label are derived from the same value retrieved by splitting the content of the cell "Subjects"**). This crm:E41_Appellation would then carry the actual string value (e.g., "ermafrodita") via the property crm:P190_has_symbolic_content. Figure 4 presents a visual representation of our intended structure, and Figure 5 shows the corresponding RDF for the example mentioned above.

<img width="997" alt="image" src="https://github.com/user-attachments/assets/af18444c-e80c-415c-a162-d2179ecc3186" />

Figure 4

<img width="746" alt="image" src="https://github.com/user-attachments/assets/3916bdbd-6f20-4079-87b6-78b79a0c3abb" />

Figure 5

Which type of approach would you suggest to use, to optimise the pipeline and avoid writing unnecessary mapping rules? 

Any guidance you may provide will be widely appreciated. 

Thank you very much.
