### ISSUE TITLE
BUG: YARRRML functions do not generate IRIs when using the "type: iri" statement

### ISSUE THREAD

**Issue by paoespinozarias** [morph-kgc/morph-kgc#181]
####  What Happens?
Applying a function on the predicate and setting the output to be an iri does not work and morph-kgc is generating a string.

#### To Reproduce

This is an illustrative example of a function applied on the predicate. Let's assume that file.csv contains an _ID_ and _Country_ columns which contains string values:

```
ID | Country | 
-- | -- | 
001 | Spain
002 | Brazil
```

Then, let's asume that there is a udf which get the IRI of a country from an external graph using the _Country_ string value to find the correct one. Then, let's assume that the mapping looks as follows:

``` YAML
prefixes:
  my_onto: https://example.com/ontology/
  my_data: https://example.com/data/
  udf_functions: https://example.com/myFunctions/
  grel: http://users.ugent.be/~bjdmeest/function/grel.ttl#

sources:
  dataSource: 
   - file.csv
    
mappings:
  Companies:
    sources: dataSource
    s: my_data:Company_$(ID)
    po:
      - [rdf:type, my_onto:Company]
       - p: my_onto:locatedAt 
         o:
          - function: udf_functions:getCountryIRIs
            parameters:
            - parameter: grel:valueParam
              value: $(Country)
            type: iri
```

The expected output is:

```
<https://example.com/data/001> a my_onto:Company ;
    my_onto:locatedAt  <https://example.com/external_ontology/Spain> .

<https://example.com/data/002> a my_onto:Company ;
    my_onto:locatedAt  <https://example.com/external_ontology/Brazil> .

```

However, I'm getting this (string values):

```
<https://example.com/data/001> a my_onto:Company ;
    my_onto:locatedAt  "https://example.com/external_ontology/Spain" .

<https://example.com/data/002> a my_onto:Company ;
    my_onto:locatedAt  "https://example.com/external_ontology/Brazil" .

```

I think that the problem is "_type: iri_" statement is not processed by morph-kgc.

It's worth mentioning that a configuration similar to the one described in the following example described in the [YARRRML specification](https://rml.io/yarrrml/spec/) is correctly processed by morph-kgc.

```
EXAMPLE 65: mapping with object that generates an IRI
mappings:
  person:
    predicateobjects:
      - predicates: foaf:knows
        objects:
          value: $(colleague)
          type: iri
```

So the  "_type: iri_" statement is working in other cases but not when is applied in functions.

#### Environment (please complete the following information):
OS: Windows 10
Python version: 3.9.6
Morph-KGC version: 2.6.2
