### ISSUE TITLE
Unable to read ORC files

### ISSUE THREAD

**Issue by jonashalv** [morph-kgc/morph-kgc#191]
####  What Happens?
There is a bug that prevents morph-kgc from reading ORC files

#### To Reproduce
Given the following: 

[dummy.orc], constructed as follows:
```
users_df = pd.DataFrame({'Id': [1,2,3,4],\
                      'Username': ["@jude","@emily","@wayne","@jordan1"], \
                      'Name': ["Jude", "Emily", "Wayne", "Jordan"],\
                      'Surname': ["White", "Van de Beeck", "Peterson", "Stones"]})

users_df.to_orc(path='dummy.orc',engine='pyarrow')
```

[test.yarrrml]
```
prefixes:
  foaf: http://xmlns.com/foaf/0.1/
  ex: http://example.com/
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  xsd: http://www.w3.org/2001/XMLSchema#

mappings:
  TM1:
    sources:
      - [dummy.orc~orc]
    s: http://example.com/$(Name)
    po:
      - [foaf:name, $(Surname)]
```

[config.ini]
```
[Test data]
mappings: ./test.yarrrml
```

Then the following python code fails:
```
g_rdflib = morph_kgc.materialize('./config.ini')
```

Error:
```
TypeError: read_table() got an unexpected keyword argument 'encoding'
```

Stripping the `encoding` parameter from the call 
```return pd.read_orc(rml_rule['logical_source_value'], encoding='utf-8', columns=references)``` in line 98 in `morph_kgc/data_source/data_file.py` makes it work though...

#### Environment (please complete the following information):
 - OS: Ubuntu 22.04 LTS
 - Python version: 3.10.12
 - Morph-KGC version: 2.6.3
 - Pandas version 2.1.1
