### ISSUE TITLE
Generate a ttl file with different named graphs

### ISSUE THREAD

**Issue by TereLaguinge** [morph-kgc/morph-kgc#208]
Hi! 

Is there a way to generate a ttl file that has triples under different named graphs using morph-kgc in python? I want to generate a ttl file like this

@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix ex: <http://example.org/> .

ex:subject123 rdf:type ex:ExampleClass .

ex:ExampleGraphValueSource1/annotation {
    ex:subject123 ex:hasValue 45464 .
}

ex:ExampleGraphValue123/annotation ex:hasAuthor "Matt";
ex:hasDate 05/03/2020;
ex:hasSource ex:Source1.

ex:ExampleGraphValueSource2/annotation {
    ex:subject123 ex:hasValue 45899 .
}

ex:ExampleGraphValueSource2/annotation ex:hasAuthor "Fred";
ex:hasDate 05/11/2022;
ex:hasSource ex:Source2.

I tried using _graph_ in my yml file but didn't work.

**Comment by arenas-guerrero-julian** [comment]
Hi @TereLaguinge ,

The system only supports N-Quads. It must be noted that an N-Quads file is a valid turtle file.

**Comment by TereLaguinge** [comment]
Hi @arenas-guerrero-julian!

I tried it using this mapping file:
`prefixes:
  rr: http://www.w3.org/ns/r2rml#
  map: http://mapping.example.com/
  rml: http://semweb.mmlab.be/ns/rml#
  ql: http://semweb.mmlab.be/ns/ql#
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  xsd: http://www.w3.org/2001/XMLSchema#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  def: http://ontology.net/def/
  skos: http://www.w3.org/2004/02/skos/core#

sources:
  main-source: ['data.xml~xpath', 'item']

mappings:
  ClinicalStudy:
    sources:
      - main-source
    s: https://ontology.net/data/Study/$(id)
    po:
      - [skos:exactMatch, $(entityIdentifiers/entityURI)~iri]
      - [[rdfs:label,def:id], $(protocolid), xsd:string]
      - [rdf:type, def:Study~iri]
      - p: def:hasNumber
        o: 
          value: $(enrichmentsData/number)
          datatype: xsd:int
          g: https://ontology.net/def/study/hasNumber/provenance`

And I run this code in python:

`config = f"""[CONFIGURATION]
    output_format=N-QUADS
    [DataSourceXML]
    mappings={mapping_file_path}
    file_path={input_xml}"""
    
    file_transformed = morph_kgc.materialize_oxigraph(config)
    #save file
    print('saving file....')
    file_transformed.dump(output_file, "application/n-quads")
`

I have donloaded morph-kgc using pip install _git+https://github.com/morph-kgc/morph-kgc.git_

But I still just get the triples and I dont get quads. Is there sth I am doing wrong?

**Comment by arenas-guerrero-julian** [comment]
Hi @TereLaguinge ,

I think that the problem is in the **indentation** of `g`. Try with:

```yml
mappings:
  ClinicalStudy:
    sources:
      - main-source
    s: https://ontology.net/data/Study/$(id)
    po:
      - [skos:exactMatch, $(entityIdentifiers/entityURI)\~iri]
      - [[rdfs:label,def:id], $(protocolid), xsd:string]
      - [rdf:type, def:Study~iri]
      - p: def:hasNumber
        o: 
          value: $(enrichmentsData/number)
          datatype: xsd:int
        g: https://ontology.net/def/study/hasNumber/provenance
```
