### ISSUE TITLE
ENH: Specify relational database through RML data source

### ISSUE THREAD

**Issue by idomingu** [morph-kgc/morph-kgc#226]
Currently, relational databases are configured as data sources via the mandatory property `db_url` in the INI file. This is detailed in the documentation here: https://morph-kgc.readthedocs.io/en/latest/documentation/#relational-databases

I propose extending Morph-KGC to support the configuration of relational databases via RML/YARRRML mapping. In this sense, users could declare relational databases in YARRRML as indicated in the YARRRML spec: https://rml.io/yarrrml/spec/#examples

For example, a MySQL database could be configured as a data sources as follows (extracted from the spec):

```yaml
#EXAMPLE 15: mapping with database as source
mapping:
  person:
    sources:
      access: http://localhost/example
      type: mysql
      credentials:
        username: root
        password: root
      queryFormulation: sql2008
      query: |
        SELECT DEPTNO, DNAME, LOC,
        (SELECT COUNT(*) FROM EMP WHERE EMP.DEPTNO=DEPT.DEPTNO) AS STAFF
        FROM DEPT;
      referenceFormulation: csv
```

With this extension, the configuration of relational databases in Morph-KGC would align with the approach followed for Data File sources, whose URL location can be specified either via RML mapping or via `file_path` property in the INI file: https://morph-kgc.readthedocs.io/en/latest/documentation/#data-files
