### ISSUE TITLE
YARRRML conditions on objects are not correctly processed

### ISSUE THREAD

**Issue by david-martinez-garcia** [morph-kgc/morph-kgc#241]
#### What happens and steps to reproduce:
I need to generate condition-based triples depending on a certain value in my data source. To learn how to do that, I have been playing with the default example provided in [YARRRML's Matey](https://rml.io/yarrrml/matey/).

This is the example data source (in JSON format):

```json
{
    "persons": [
        {
            "firstname": "John",
            "lastname": "Doe"
        },
        {
            "firstname": "Jane",
            "lastname": "Smith"
        },
        {
            "firstname": "Sarah",
            "lastname": "Bladinck"
        }
    ]
}
```

I want to generate a predicate `ex:is_smith` with object value `true` when the property `lastname` is `Smith`, and `false` otherwise. So, I have edited the mapping rules accordingly:

```yaml
prefixes:
 ex: "http://example.com/"
 grel: "http://users.ugent.be/~bjdmeest/function/grel.ttl#"
 idlab-fn: "http://example.com/idlab/function/"

mappings:
  person:
    sources:
      - ['data.json~jsonpath', '$.persons[*]']
    s: http://example.com/$(firstname)
    po:
      - [a, foaf:Person]
      - [ex:name, $(firstname)]
      - p: ex:is_smith
        o:
          - value: "true"
            datatype: xsd:boolean
            condition:
              function: equal
              parameters:
                - [str1, $(lastname)]
                - [str2, "Smith"]
          - value: "false"
            datatype: xsd:boolean
            condition:
              function: idlab-fn:notEqual
              parameters:
                - [grel:valueParameter, $(lastname)]
                - [grel:valueParameter2, "Smith"]
```

With Matey this works as expected, and the following triples are generated:

```turtle
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix sd: <http://www.w3.org/ns/sparql-service-description#> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix ex: <http://example.com/> .
@prefix grel: <http://users.ugent.be/~bjdmeest/function/grel.ttl#> .
@prefix idlab-fn: <http://example.com/idlab/function/> .

ex:John rdf:type foaf:Person ;
	ex:name "John" ;
	ex:is_smith "false"^^xsd:boolean .

ex:Jane rdf:type foaf:Person ;
	ex:name "Jane" ;
	ex:is_smith "true"^^xsd:boolean .

ex:Sarah rdf:type foaf:Person ;
	ex:name "Sarah" ;
	ex:is_smith "false"^^xsd:boolean .
```

However, if I try to run the same example with Morph, the output is wrong:

```rdf
<http://example.com/Sarah> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "foaf:Person" .
<http://example.com/Jane> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "foaf:Person" .
<http://example.com/John> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "foaf:Person" .
<http://example.com/John> <http://example.com/name> "John" .
<http://example.com/Sarah> <http://example.com/name> "Sarah" .
<http://example.com/Jane> <http://example.com/name> "Jane" .
<http://example.com/John> <http://example.com/is_smith> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://example.com/Jane> <http://example.com/is_smith> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://example.com/Jane> <http://example.com/is_smith> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://example.com/John> <http://example.com/is_smith> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://example.com/Sarah> <http://example.com/is_smith> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://example.com/Sarah> <http://example.com/is_smith> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
```

As you can see, it is generating two `ex:is_smith` triples per subject, one with object value `true` and another with object value `false`, when there should be just one triple per subject with only one object value. The expected output should be the following:

```rdf
<http://example.com/John> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "foaf:Person" .
<http://example.com/Jane> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "foaf:Person" .
<http://example.com/Sarah> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "foaf:Person" .
<http://example.com/John> <http://example.com/name> "John" .
<http://example.com/Jane> <http://example.com/name> "Jane" .
<http://example.com/Sarah> <http://example.com/name> "Sarah" .
<http://example.com/John> <http://example.com/is_smith> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://example.com/Jane> <http://example.com/is_smith> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://example.com/Sarah> <http://example.com/is_smith> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
```

#### Environment (please complete the following information):
 - OS: Ubuntu 22.04 LTS
 - Python version: 3.10.12
 - Morph-KGC version: 2.7.0

Thanks.

**Comment by arenas-guerrero-julian** [comment]
Hi @david-martinez-garcia,

Morph-KGC does not currently support that YARRRML syntax. However, you can do it by using the following:

```yaml
prefixes:
 ex: "http://example.com/"
 grel: "http://users.ugent.be/~bjdmeest/function/grel.ttl#"
 idlab-fn: "http://example.com/idlab/function/"

mappings:
  person:
    sources:
      - access: data.json
        referenceFormulation: jsonpath
        iterator: $.persons[*]
    s: http://example.com/$(firstname)
    po:
      - [a, foaf:Person]
      - [ex:name, $(firstname)]
      - p: ex:is_smith
        o:
          - f: grel:controls_if
            datatype: xsd:boolean
            parameters:
              - [grel:bool_b, "'Smith' == '$(lastname)'"]
              - [grel:any_true, "true"]
              - [grel:any_false, "false"]

```
