### ISSUE TITLE
Error on YARRRML mappings when creating a condition

### ISSUE THREAD

**Issue by igrangel** [morph-kgc/morph-kgc#253]
####  What Happens?
I'm connecting to a MS SQL data base and all mappings are working fine. Even, when I call python functions to do transformations on top of the data they are also working fine, e.g., input the field value and return the field in lowercase as the simplest example. 
I want to use a condition so that when the value of a given field is null or an empty field I do not create that triple. 

#### To Reproduce
This is the mapping excerpt that I'm using:

 ```
mapping:
    sources: ds
    s: http://uri.com/ds-$(id)
    po:
      - [a, onto:Entity]
      - p: onto:description
        o: 
        condition:
          function: ex:isValid
          parameters:
            - [text, $(field_value_from_db)]
```

The python function:

```
@udf(
    fun_id='http://example.com/isValid',
    text='http://users.ugent.be/~bjdmeest/function/grel.ttl#valueParam')
def isValid(text):
    if text is None or text.strip() == "":
        return False
    return text
```

With that mapping I got the following error:

`Exception: argument of type 'NoneType' is not iterable`

I have used this version of mappings as well

 ```
mapping:
    sources: ds
    s: http://uri.com/ds-$(id)
    po:
      - [a, onto:Entity]
      - p: onto:description
        o: 
        - condition:
            function: ex:isValid
            parameters:
              - parameter: grel:valueParam
              value: $(field_value_from_db)
```

With that mappings I got the following error:

`raise Exception(yaml_parse_exception) Exception: 'value'`

#### Environment (please complete the following information):
 - OS: Windows 11
 - Python version: 3.10
 - Morph-KGC version: 2.7.0

Would be great to have your suggestions support here.

**Comment by arenas-guerrero-julian** [comment]
Hi @igrangel ,

If you want to filter values you should return `None` instead of `False` in your UDF. We describe this in [this article](https://www.sciencedirect.com/science/article/pii/S2352711024000803): "*To filter values in a UDF, None can be returned, in which case the RML-FNML module will not generate triples for those values*". If this is helpful I can also add it to the docs in the RML-FNML section. In your case, your UDF should look like this:

```python
@udf(
    fun_id='http://example.com/isValid',
    text='http://users.ugent.be/~bjdmeest/function/grel.ttl#valueParam')
def isValid(text):
    if text is None or text.strip() == "":
        return None
    return text
```

In Python, when there is no `return` clause, `None` is returned and non-empty strings evaluate to `True`, so the UDF could be simplified as:

```python
@udf(
    fun_id='http://example.com/isValid',
    text='http://users.ugent.be/~bjdmeest/function/grel.ttl#valueParam')
def isValid(text):
    if text and text.strip():
        return text
```

Regarding your latter issue, please, mind indentation in YARRRML:

```yml
mapping:
   sources: ds
   s: http://uri.com/ds-$(id)
   po:
     - [a, onto:Entity]
     - p: onto:description
       o: 
       - condition:
           function: ex:isValid
           parameters:
             - parameter: grel:valueParam
               value: $(field_value_from_db)  # <<<<<<< correct indentation
```
