### ISSUE TITLE
iterate over an array returned by the BIF string_split(string, separator) on the value of a CSV column

### ISSUE THREAD

**Issue by ariannamorettj** [morph-kgc/morph-kgc#279]
Hi!
I'm using morph-kgc on a CSV file. 
I'm trying to understand how to iterate over the values returned by the built-in function string_split(string, separator), applied to the value of a column of the CSV input file. 

The function returns an array of strings by splitting the input string at separator:

`@bif(
    fun_id='http://users.ugent.be/~bjdmeest/function/grel.ttl#string_split',
    string='http://users.ugent.be/~bjdmeest/function/grel.ttl#valueParam',
    separator='http://users.ugent.be/~bjdmeest/function/grel.ttl#param_string_sep')
def string_split(string, separator):
    return str(string.split(separator))` 
    
The cell of the input CSV file I'm working with: 
| Soggetti |
|--------|
| Amerigo Vespucci; astrolabio; vessillo Croce del sud; formichiere; bradipo; tapiro; gruppo di cannibali |

The mapping I tried to produce (which doesn't work)

```
subject_mapping:
  sources:
    - 'sample_input_file.csv~csv'
    - iterator: "$.s[*]"
  s:
    function: idlab-fn:string_split
    parameters:
      - parameter: idlab-fn:valueParam
        value: $(Soggetti)
      - parameter: idlab-fn:param_string_sep
        value: ";"
  po:
    - [ a, "crm:E73_Information_Object" ]
    - ["crm:P2_has_type", "aat:300404126"]
``` 

Could you provide guidance on this?
Sorry in case a similar issue was already presented, I could not find the answer to my questions in the ones I checked. 

Thank you very much in advance for your help!

**Comment by ariannamorettj** [comment]
Thank you very much @arenas-guerrero-julian for your answer!

I read both the articles you suggested, but I still have doubts concerning the possibility of solving my problem using a query or a user-defined function. 
More in detail, I would use a UDF or a query to retrieve the list of subjects, but I still couldn't iterate over the obtained list of subjects, to produce as many triples as the number of retrieved entities (if I understood correctly). 

Indeed, I would need an iteration mechanism equivalent to [the one used on nested JSON structures](https://rml.io/yarrrml/spec/#iterator), to be applied to the result of a function. In detail, this is what I tried to represent with `"$.s[*]"`, where "s" is meant to be the result of the function executed in the subject mapping. 

```
  s:
    function: idlab-fn:string_split
    parameters:
      - parameter: idlab-fn:valueParam
        value: $(Soggetti)
      - parameter: idlab-fn:param_string_sep
        value: ";"
``` 
As expected, I get an error when I try to use this mapping, without obtaining any output.
As a further step, I will certainly read more in detail the bibliography of the proposed articles, but before that, I would like to understand if an iteration mechanism addressing this necessity is already developed in Morph-kgc. 

A similar issue (not concerning the iteration mechanism, but the possibility of using the result of a function to fill another field of the mapping, instead of directly specifying the value in the mapping) is that of the language field. I would like to automatically extract the language from a csv column by using a user-defined function, but I haven’t found a mechanism that allows me to use the result of the function as the value of the “language” field of the YARRRML mapping. 

Could you please provide further guidance concerning the aforementioned aspects?

Again, Thank you very much for your help.

**Comment by arenas-guerrero-julian** [comment]
Could you provide the RDF output that you want to generate in your example?

Regarding your secong issue I think it is complicated right now. I think that you want to first detect the language of an entire column, which I believe is more an aggregate funtion that is not currently possible. What I assume you can do is to have a UDF that detects the language of a cell and return that value in a language map.

**Comment by ariannamorettj** [comment]
Yes of course. 

An example of the result I would like to obtain, when the subject is one, is this: 

```
ex:ermafrodita a crm:E73_Information_Object ;
    crm:P2_has_type aat:300404126 .
``` 

In this case, I can easily obtain this result from an input table like this: 

| Soggetti |
|--------|
| ermafrodita | 

using this simple mapping: 

```
  subject_mapping:
    sources:
      - 'sample_input_file.csv~csv'
    s: "ex:$(Soggetti)"
    po:
      - [ a, "crm:E73_Information_Object" ]
      - ["crm:P2_has_type", "aat:300404126"]

``` 

The problem is when there is more than one subject, and my input table is the same as the one I presented in the first comment on this issue. 
In that case, the result I would like to obtain is this one : 

```
ex:Amerigo_Vespucci a crm:E73_Information_Object ;
    crm:P2_has_type aat:300404126 .

ex:astrolabio a crm:E73_Information_Object ;
    crm:P2_has_type aat:300404126 .

ex:vessillo_Croce_del_sud a crm:E73_Information_Object ;
    crm:P2_has_type aat:300404126 .

ex:formichiere a crm:E73_Information_Object ;
    crm:P2_has_type aat:300404126 .

ex:bradipo a crm:E73_Information_Object ;
    crm:P2_has_type aat:300404126 .

ex:tapiro a crm:E73_Information_Object ;
    crm:P2_has_type aat:300404126 .

ex:gruppo_di_cannibali a crm:E73_Information_Object ;
    crm:P2_has_type aat:300404126 .
``` 

Indeed, the aim is to produce the same group of triples determined by the mapping for each of the retrieved subjects (the upper/lower case normalization and the underscores addition are secondary issues that I can easily manage with an udf).

Again, thank you very much for your availability and guidance.
