### ISSUE TITLE
NQuads serialization only makes sense for context-aware stores!

### ISSUE THREAD

**Issue by Crispae** [morph-kgc/morph-kgc#280]
####  What Happens?
I want to serialize my kG with Graph, some issue with rdflib
![image](https://github.com/user-attachments/assets/a74cce4f-ffe2-4ab8-a5c8-3debc2cac142)

#### To Reproduce
Data:
```
{
    "data": [
        {
            "objectID": "142c210e-1c60-44e4-b235-f4f242b70e9f",
            "ID": "281",
            "Title": "Thyroxine (T4) in serum, Decreased",
            "ShortName": "T4 in serum, Decreased",
            "Description": "test1",
            "Measurement&DetectionTechniques": "test2",
            "ApplicabilityDomain": "test3"
        }
    ]
}
 ```

Mapping:
```
prefixes:
  rml: "http://semweb.mmlab.be/ns/rml#"
  rr: "http://www.w3.org/ns/r2rml#"
  ql: "http://semweb.mmlab.be/ns/ql#"
  rdf: "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
  rdfs: "http://www.w3.org/2000/01/rdf-schema#"
  schema: "http://schema.org/"
  dbo: "http://dbpedia.org/ontology/"
  aop: "http://aop.org/ontology/"
  dc: "http://purl.org/dc/elements/1.1/"

sources:
  source0:
    referenceFormulation: jsonpath
    iterator: "$.data[*]"

    
mappings:

  KeyEventMapping:
    sources:
      - source0
    s: 
      value: http://www.example.com/keyEvent/$(ID)
    graphs: "aop:myGraph"

    po:
      - [rdf:type, aop:assertion]
      - [dc:title, "$(Title)"]
      - [aop:short-name, "$(ShortName)"]
      - [dc:Description, "$(Description)"]
      - [aop:ApplicabilityDomain,"$(ApplicabilityDomain)"]
      - [aop:Measurement&DetectionTechniques ,"$(Measurement&DetectionTechniques)"]

```

#### Environment (please complete the following information):
 - OS: Windos
 - Python version: [e.g. 3.9]
 - Morph-KGC version: [e.g. 2.8.0]
