### ISSUE TITLE
The `xsd:integer` datatype is not working properly when used in YARRRML mappings of a MS SQL Server source

### ISSUE THREAD

**Issue by igrangel** [morph-kgc/morph-kgc#282]
####  What Happens?
The `xsd:integer` datatype is not working properly when used in the YARRRML mappings. 

#### To Reproduce
I'm querying a MS SQL Server database, the query is simple, you can think of like `SELECT field1, field2 FROM table1`

```
mapping1:
    sources: mssql
    s: ont:class1-instance$(Id)
    po:
      - [a, ont:Class1]
      - [onto:propertyOneOfTypeInteger, $(Id), xsd:integer]
```

If we use `xsd:int` or `xsd:Integer` (please note the wrong `I` in `xsd:Integer`), even `xsd:float` it works, but If I use it like `xsd:integer` the datatype is not attached to the generated triple. 

#### Environment (please complete the following information):
 - OS: [e.g. Windows 10]
 - Python version: [e.g. 3.10]
 - Morph-KGC version: [e.g. 2.7.0]
