### ISSUE TITLE
UDFs will not work if column name starts with 'function'

### ISSUE THREAD

**Issue by neobernad** [morph-kgc/morph-kgc#310]
####  What Happens?
Error arises:

```python
File "C:\...\morph_kgc\mapping\yarrrml.py", line 211, in _normalize_function_parameters
    elif term_map['function'].endswith(')'):
         ~~~~~~~~^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'

```

#### To Reproduce
CSV with column name starting by `function`, e.g. `functionallocation`. Actually anything starting like `function*` triggers the same error. Changing the column name to "funtional" or "functio" (removing a character works), but changing a data source column name is not always possible.

Example UDF:

```python
@udf(
    fun_id='https://example.com/hash_iri',
    string='http://users.ugent.be/~bjdmeest/function/grel.ttl#valueParam',
    ns='http://users.ugent.be/~bjdmeest/function/grel.ttl#ns'
)
def hash_iri(string, ns):
    return f'{ns}' f'{hash(string)}'

@udf(
    fun_id='https://example.com/hash',
    string='http://users.ugent.be/~bjdmeest/function/grel.ttl#valueParam'
)
def hash(string):
    return f'{sha256(string.encode("UTF-8")).hexdigest()[:12]}'
```

Example mapping:

```yaml
prefixes:
  grel: http://users.ugent.be/~bjdmeest/function/grel.ttl#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  ex: https://example.com/
  base_ont: https://example.com/ontology/Test/
  base_data: https://example.com/data/Test/


sources:
  FunctionalLocation:
    - data/Anon_functionallocation_10.csv~csv

mappings:

  FunctionalLocationMappings:
    sources: FunctionalLocation

    s:
      - function: ex:hash_iri
        parameters:
          - [ grel:valueParam, "FunctionalLocation_$(function)" ]
          - [ grel:ns, "https://example.com/data/Test/PlantMaintenance/" ]
        type: iri
    po:
      - [ a, base_ont:FunctionalLocation ]
      - [ rdfs:label, $(function) ]
```

#### Environment (please complete the following information):
 - OS: Windows 11
 - Python version: 3.12
 - Morph-KGC version: 2.8.0 (also happens in  2.8.1)
