### ISSUE TITLE
Function on datatype

### ISSUE THREAD

**Issue by paoespinozarias** [morph-kgc/morph-kgc#314]
### What happens?

In some cases, you need to define values with custom datatypes, which are usually defined in an ontology. Therefore, to obtain the custom datatypes it is necessary to query the ontology using a UDF in the datatype mapping rule. 

To cover these scenarios, it would be useful for morph-kgc to support the execution of a `function` on `datatype`: 

```
Mapping:
    sources: XXXXXX
    s: XXXXXX
    po:
      - p: XXXXXXXX
        o:
          - value: "X"
            datatype:
              - function: XXXXX
                parameters:
                  - [ X, X ]
                type: iri
```

### To reproduce

In the following, I provide a set of files aiming to illustrate the input file, custom datatypes ontology, mappings and the desired ouput. It is assumed in this example that morph-kgc supports a `function` on `datatype`.

Example Datasource (file.csv):

```
Material | Value | Unit | 
-- |-- | -- | 
1|1676| kg-m3
2|1234 | kg-l
```

Example custom datatypes ontology:
```
@prefix ontology:   <http://example.com/ontology/> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

ontology:kg-m3 a rdfs:Datatype;
        rdfs:label "Kilogram per metric cube datatype";
        rdfs:comment "A datatype to type densities measured in kilogram per meter cube" ;
        ontology:hasSymbol "kg-m3" .

ontology:kg-l a rdfs:Datatype;
        rdfs:label "Kilogram per liter datatype";
        rdfs:comment "A datatype to type densities measured in kilogram per liter cube" ;
        ontology:hasSymbol "kg-l" .
```

Example UDF:
```
@udf(
    fun_id='http://example.com/mappingfunction/get_unit',
    unit='http://users.ugent.be/~bjdmeest/function/grel.ttl#valueParam'
)
def get_unit(unit: str):
    query = f"""
                PREFIX custom_onto: <http://example.com/ontology/>
                SELECT DISTINCT ?custom_datatype
                FROM <http://example.com/ontology>
                WHERE {{
                    ?custom_datatype rdf:type rdfs:Datatype  ;
                           custom_onto:hasSymbol ?symbol  .
                    FILTER (?symbol = "{unit}")
                }}               
            """
    result = sparql_service.query(query)
    if result and result['results']['bindings']:
        return result['results']['bindings'][0]['custom_datatype']['value']
    return "UnknownUnit"
```

Example Mapping: 

```
prefixes:
  data: http://example.com/data/ 
  ontology: http://example.com/ontology/ 
  mappingfunction: http://example.com/mappingfunction/
  grel: http://users.ugent.be/~bjdmeest/function/grel.ttl#

sources:
  dataSource: [file.csv]

mappings:

  Materials:
    sources: dataSource
    s: data:Material$(Material)
    po:
      - [ rdf:type, ontology:Material ]
      - p: ontology:density
        o:
          - value: $(Value)
            datatype:
              - function: mappingfunction:get_unit
                parameters:
                  - [ grel:valueParam, $(Unit) ]
                type: iri
```

Expected output:
```
@prefix data:  <http://example.com/data/> .
@prefix o:   <http://example.com/ontology/> .

data:Material1 a ontology:Material;
     ontology:density "1676"^^ontology:kg-m3 .

data:Material2 a ontology:Material;
     ontology:density "1234"^^ontology:kg-l .
```

### OS:

Windows 11

### Morph-KGC version:

2.8.1

### Full name:

Paola Espinoza

### Affiliation:

BASF

### Did you include all relevant data sets for reproducing the issue?

No - I cannot share the data sets because they are confidential

### Did you include all mappings and code required to reproduce the issue?

- [x] Yes, I have
