### ISSUE TITLE
Built-In Function does not use fno:predicate

### ISSUE THREAD

**Issue by achiminator** [morph-kgc/morph-kgc#320]
### What happens?

Hey there!
While using the build-in `grel` functions, I stumbled upon an inconsistent use of the parameters. As I understood the [FNO](https://fno.io/spec/#fn-parameter)-Spec and the https://fno.io/rml/ description, the parameter must contain `fno:predicate` to mark how to call a respective parameter of a function. Thus, the `fno:predicate`-URI should be used to call the given value. Unfortunately, the [built-in functions](https://github.com/morph-kgc/morph-kgc/blob/main/src/morph_kgc/fnml/built_in_functions.py) use the URI of the parameter type, instead of the `fno:predicate`. 

Switching the behavior would probably break a lot of pipelines. But maybe we can add the `fno:predicate` as an alternative for calling the functions? That would also make morph-kgc more compatible to the RML-Mapper.

### To reproduce

Example: `grel:string_replace` is called in morph-kgc as follows. The URI of the parameters is being used.
```yaml                  function: grel:string_replace
                  parameters:
                      - parameter: grel:valueParam
                        value: $(Model)
                      - parameter: grel:param_find
                        value: Co
                      - parameter: grel:param_replace
                        value: li
```

However, it should be, from my understanding the `fno:predicate`. That is also the way it is implemented in [RML-Mapper](https://github.com/RMLio/rmlmapper-java).:

```yaml                  function: grel:string_replace
                  parameters:
                      - parameter: grel:valueParameter
                        value: $(Model)
                      - parameter: grel:p_string_find
                        value: Co
                      - parameter: grel:p_string_replace
                        value: li
```

### OS:

Any

### Morph-KGC version:

2.8.1

### Full name:

Achim Reiz

### Affiliation:

neonto GmbH

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all mappings and code required to reproduce the issue?

- [x] Yes, I have
