### ISSUE TITLE
YARRRML should contain rdfa prefixes.

### ISSUE THREAD

**Issue by achiminator** [morph-kgc/morph-kgc#328]
### What happens?

Hey @arenas-guerrero-julian ,
I found another bug I'd like to fix. YARRRML should contain the rdfa-prefixes. See the [Spec](https://rml.io/yarrrml/spec/#prefixes-and-namespaces).
Thus, a mapping like this should work, where we have not explicitly defined `schema` and `rdf`.

```yaml
prefixes:
    ex: http://example.com#
mappings:
    cars:
        sources:
            - access: cars.csv
              referenceFormulation: csv
        subjects: ex:car_$(ID)
        predicateobjects:
            - p: rdf:type
              o: ex:Car
            - p: schema:material
              o: "Metal and Plastic"
```

However, currently, we are getting a misleading error:
`Exception has occurred: ValueError
Found an invalid predicate termtype. Found values {'http://w3id.org/rml/Literal'}. Predicate maps must be http://w3id.org/rml/IRI.`

Again, I'm happy to contribute a fix.

### To reproduce

```csv
ID,Comment,Seats,Owner,Color,Year,Model
1,"A red car with 4 seats",4,9,Red,2020,Toyota Corolla
2,"A blue car with 5 seats",5,8,Blue,2019,Honda Civic
```

### OS:

any

### Morph-KGC version:

2.8.1

### Full name:

Achim Reiz

### Affiliation:

neonto GmbH

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all mappings and code required to reproduce the issue?

- [x] Yes, I have
